apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: default
spec:
  provider: azure
  parameters:
    usePodModify: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: KV_NAME
    objects: |
      array:
        - |
          objectName: symkey-wrap
          objectType: secret
          objectVersion: ""
    tenantId: TENANT_ID
